components:
- name: ElasticsearchDocumentStore
  params: {}
  type: ElasticsearchDocumentStore
- name: Retriever
  params:
    document_store: ElasticsearchDocumentStore
  type: BM25Retriever
- name: Reader
  params:
    model_name_or_path: deepset/roberta-base-squad2
  type: FARMReader
pipelines:
- name: query
  nodes:
  - inputs:
    - Query
    name: Retriever
  - inputs:
    - Retriever
    name: Reader
version: 1.10.0rc0
